// Code generated by configgen. DO NOT EDIT.
// Код сгенерирован configgen. НЕ РЕДАКТИРОВАТЬ.

package config

import "time"

// Config основная структура конфигурации
type Config struct {
	// Информация о приложении
	App App `toml:"app"`
	Db  Db  `toml:"db"`
	// Переключатели функций
	Features Features `toml:"features"`
	// Лимиты и ограничения
	Limits Limits `toml:"limits"`
	Log    Log    `toml:"log"`
	Redis  Redis  `toml:"redis"`
	Server Server `toml:"server"`
}

// Информация о приложении
// App секция конфигурации
type App struct {
	// Название сервиса
	Name string `toml:"name"`
	// Версия приложения
	Version string `toml:"version"`
}

// Db секция конфигурации
type Db struct {
	// Хост базы данных
	Host string `toml:"host"`
	// Время жизни неактивного соединения
	MaxIdleTime time.Duration `toml:"max_idle_time"`
	// Имя базы данных
	Name string `toml:"name"`
	// Пароль (в dev можно хранить в конфиге)
	Password string `toml:"password"`
	// Размер пула соединений
	PoolSize int `toml:"pool_size"`
	// Порт PostgreSQL
	Port int `toml:"port"`
	// Пользователь БД
	User string `toml:"user"`
}

// Переключатели функций
// Features секция конфигурации
type Features struct {
	// Включить сбор метрик
	EnableMetrics bool `toml:"enable_metrics"`
	// Включить трейсинг
	EnableTracing bool `toml:"enable_tracing"`
}

// Лимиты и ограничения
// Limits секция конфигурации
type Limits struct {
	// Максимальное количество одновременных соединений
	MaxConnections int `toml:"max_connections"`
	// Максимальный размер запроса в байтах (10MB)
	MaxRequestSize int `toml:"max_request_size"`
	// Таймаут обработки запроса
	RequestTimeout time.Duration `toml:"request_timeout"`
}

// Log секция конфигурации
type Log struct {
	// Формат вывода: text или json
	Format string `toml:"format"`
	// Уровень логирования: debug, info, warn, error
	Level string `toml:"level"`
}

// Redis секция конфигурации
type Redis struct {
	// Номер базы данных
	Db int `toml:"db"`
	// Хост Redis
	Host string `toml:"host"`
	// Порт Redis
	Port int `toml:"port"`
}

// Server секция конфигурации
type Server struct {
	// Адрес для прослушивания
	Host string `toml:"host"`
	// Порт сервера
	Port int `toml:"port"`
	// Таймаут на чтение запроса
	ReadTimeout time.Duration `toml:"read_timeout"`
	// Таймаут на запись ответа
	WriteTimeout time.Duration `toml:"write_timeout"`
}
