// Code generated by configgen. DO NOT EDIT.
// Код сгенерирован configgen. НЕ РЕДАКТИРОВАТЬ.

package config

import "time"

// Environment представляет окружение развертывания
type Environment string

const (
	EnvLocal      Environment = "local"
	EnvDev        Environment = "dev"
	EnvStaging    Environment = "stg"
	EnvProduction Environment = "prod"
)

// Config основная структура конфигурации
type Config struct {
	Env Environment `toml:"-"`
	// Информация о приложении
	App App `toml:"app"`
	Db  Db  `toml:"db"`
	// Переключатели функций
	Features Features `toml:"features"`
	// Лимиты и ограничения
	Limits Limits `toml:"limits"`
	Log    Log    `toml:"log"`
	Oauth  Oauth  `toml:"oauth"`
	Redis  Redis  `toml:"redis"`
	Server Server `toml:"server"`
}

func (c *Config) IsProduction() bool { return c.Env == EnvProduction }
func (c *Config) IsStg() bool        { return c.Env == EnvStaging }
func (c *Config) IsLocal() bool      { return c.Env == EnvLocal }
func (c *Config) GetEnv() string     { return string(c.Env) }

//go:generate minimock -i Configurator -o ./mock/ -s _mock.go -g

// Configurator интерфейс для мокирования конфигурации в тестах
type Configurator interface {
	IsProduction() bool
	IsStg() bool
	IsLocal() bool
	GetEnv() string
}

// Информация о приложении
type App struct {
	// Название сервиса
	Name string `toml:"name"`
	// Версия приложения
	Version string `toml:"version"`
}
type Db struct {
	// Хост базы данных
	Host string `toml:"host"`
	// Время жизни неактивного соединения
	MaxIdleTime time.Duration `toml:"max_idle_time"`
	// Имя базы данных
	Name string `toml:"name"`
	// Пароль (в dev можно хранить в конфиге)
	Password string `toml:"password"`
	// Размер пула соединений
	PoolSize int `toml:"pool_size"`
	// Порт PostgreSQL
	Port int `toml:"port"`
	// Пользователь БД
	User string `toml:"user"`
}

// Переключатели функций
type Features struct {
	// Включить сбор метрик
	EnableMetrics bool `toml:"enable_metrics"`
	// Включить трейсинг
	EnableTracing bool `toml:"enable_tracing"`
}

// Лимиты и ограничения
type Limits struct {
	// Максимальное количество одновременных соединений
	MaxConnections int `toml:"max_connections"`
	// Максимальный размер запроса в байтах (10MB)
	MaxRequestSize int `toml:"max_request_size"`
	// Таймаут обработки запроса
	RequestTimeout time.Duration `toml:"request_timeout"`
}
type Log struct {
	// Формат вывода: text или json
	Format string `toml:"format"`
	// Уровень логирования: debug, info, warn, error
	Level string `toml:"level"`
}
type Oauth struct {
	Github OauthGithub `toml:"github"`
	Vk     OauthVk     `toml:"vk"`
}
type OauthGithub struct {
	ClientId    string `toml:"client_id"`
	RedirectUrl string `toml:"redirect_url"`
}
type OauthVk struct {
	ClientId    string `toml:"client_id"`
	RedirectUrl string `toml:"redirect_url"`
}
type Redis struct {
	// Номер базы данных
	Db int `toml:"db"`
	// Хост Redis
	Host string `toml:"host"`
	// Порт Redis
	Port int `toml:"port"`
}
type Server struct {
	// Адрес для прослушивания
	Host string `toml:"host"`
	// Порт сервера
	Port int `toml:"port"`
	// Таймаут на чтение запроса
	ReadTimeout time.Duration `toml:"read_timeout"`
	// Таймаут на запись ответа
	WriteTimeout time.Duration `toml:"write_timeout"`
}
