version: '3'

vars:
  EXAMPLE_DIR: ./example/service
  EXAMPLE_CONFIGS: ./example/service/configs
  EXAMPLE_OUTPUT: ./example/service/internal/config

  DEV_TOOLS: |
    github.com/gojuno/minimock/v3/cmd/minimock@latest

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  MINIMOCK: "{{.BIN_DIR}}/minimock"

env:
  APP_ENV: prod

tasks:
  install:
    desc: "Устанавливает все инструменты разработки"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - for: { var: DEV_TOOLS }
        cmd: GOBIN="{{.BIN_DIR}}" go install "{{ .ITEM }}"

  test:
    desc: Запуск всех тестов
    cmds:
      - go test ./...

  build:
    desc: Сборка configgen
    cmds:
      - go build ./cmd/configgen

  generate-config:
    desc: Генерация конфигов для example/service
    cmds:
      - go run ./cmd/configgen --configs={{.EXAMPLE_CONFIGS}} --output={{.EXAMPLE_OUTPUT}} --package=config --init

  mock:gen:
    desc: Генерация моков (go generate)
    dir: "{{.EXAMPLE_DIR}}"
    cmds:
      - PATH="{{.BIN_DIR}}:$PATH" go generate ./internal/config/...

  example:run:
    desc: Запуск example/service
    dir: "{{.EXAMPLE_DIR}}"
    cmds:
      - go run main.go

  example:build:
    desc: Сборка example/service
    dir: "{{.EXAMPLE_DIR}}"
    cmds:
      - go build ./...

  all:
    desc: Тесты + генерация + моки + сборка example
    cmds:
      - task: test
      - task: generate-config
      - task: mock:gen
      - task: example:build
