// Code generated by MockGen. DO NOT EDIT.
// Source: ./example/service/internal/config/config.gen.go
//
// Generated by this command:
//
//	mockgen -source=./example/service/internal/config/config.gen.go -destination=./example/service/internal/config/mock/mock_config.gen.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfigurator is a mock of Configurator interface.
type MockConfigurator struct {
	ctrl     *gomock.Controller
	recorder *MockConfiguratorMockRecorder
	isgomock struct{}
}

// MockConfiguratorMockRecorder is the mock recorder for MockConfigurator.
type MockConfiguratorMockRecorder struct {
	mock *MockConfigurator
}

// NewMockConfigurator creates a new mock instance.
func NewMockConfigurator(ctrl *gomock.Controller) *MockConfigurator {
	mock := &MockConfigurator{ctrl: ctrl}
	mock.recorder = &MockConfiguratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurator) EXPECT() *MockConfiguratorMockRecorder {
	return m.recorder
}

// GetEnv mocks base method.
func (m *MockConfigurator) GetEnv() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnv")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetEnv indicates an expected call of GetEnv.
func (mr *MockConfiguratorMockRecorder) GetEnv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnv", reflect.TypeOf((*MockConfigurator)(nil).GetEnv))
}

// IsLocal mocks base method.
func (m *MockConfigurator) IsLocal() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLocal")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLocal indicates an expected call of IsLocal.
func (mr *MockConfiguratorMockRecorder) IsLocal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLocal", reflect.TypeOf((*MockConfigurator)(nil).IsLocal))
}

// IsProduction mocks base method.
func (m *MockConfigurator) IsProduction() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProduction")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProduction indicates an expected call of IsProduction.
func (mr *MockConfiguratorMockRecorder) IsProduction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProduction", reflect.TypeOf((*MockConfigurator)(nil).IsProduction))
}

// IsStg mocks base method.
func (m *MockConfigurator) IsStg() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStg")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStg indicates an expected call of IsStg.
func (mr *MockConfiguratorMockRecorder) IsStg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStg", reflect.TypeOf((*MockConfigurator)(nil).IsStg))
}
